# Generated by Django 4.2.7 on 2023-11-22 14:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0004_alter_booking_ao_status_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee_details',
            new_name='User_details',
        ),
    ]
