# Generated by Django 4.2.7 on 2023-11-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_employee_details_user_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_details',
            old_name='employee',
            new_name='user',
        ),
        migrations.AddField(
            model_name='user_details',
            name='role',
            field=models.CharField(default='employee', max_length=50),
            preserve_default=False,
        ),
    ]
