# Generated by Django 4.2.7 on 2023-11-20 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('eligible_occupancy', models.IntegerField()),
                ('booking_days', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('participants_count', models.IntegerField()),
                ('purpose', models.CharField(max_length=200)),
                ('employee_remark', models.CharField(max_length=400)),
                ('submit_date', models.DateTimeField(auto_now_add=True)),
                ('hod_remark', models.CharField(max_length=400)),
                ('hod_approval_status', models.BooleanField()),
                ('hod_status_date', models.DateTimeField()),
                ('ao_remark', models.CharField(max_length=400)),
                ('ao_approval_status', models.BooleanField()),
                ('ao_status_date', models.DateTimeField()),
                ('ao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aoId', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employeeId', to=settings.AUTH_USER_MODEL)),
                ('employee_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detailsId', to='user.employee_details')),
                ('hall', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ConferenceHall', to='hall.conferencehall')),
                ('hod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hodId', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
