# Generated by Django 4.2.7 on 2023-11-24 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0004_alter_booking_ao_status_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conferencehall',
            name='image',
        ),
    ]
