# Generated by Django 4.2.7 on 2023-11-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0006_hallimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hallimage',
            old_name='product',
            new_name='hall',
        ),
        migrations.AlterField(
            model_name='hallimage',
            name='image',
            field=models.ImageField(upload_to='halls'),
        ),
    ]
