# Generated by Django 4.2.7 on 2023-11-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0007_rename_product_hallimage_hall_alter_hallimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('field', models.CharField(max_length=50)),
                ('route', models.CharField(max_length=100)),
            ],
        ),
    ]
