# Generated by Django 4.2.7 on 2023-12-02 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0008_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='hallimage',
            name='hall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='hall.conferencehall'),
        ),
    ]
