# Generated by Django 4.2.7 on 2023-12-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0009_homepage_order_alter_hallimage_hall'),
    ]

    operations = [
        migrations.AddField(
            model_name='hallimage',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
